### ISSUE TITLE
Changing Input text block to Range

### ISSUE THREAD

**Issue by iamwatchdogs** [iamwatchdogs/LoanApprovalPredictionModel_Website#7]
My task is review by one of my college teacher and he has suggest me to change the Input text block to Input range blocks. Something just like the following picture.

![image](https://github.com/iamwatchdogs/LoanApprovalPredictionModel_Website/assets/49478000/db0c4c9b-3775-427c-98c7-2046eaa3f301)

## Points to be noted
- Make sure the ranges are in reasonable range for the related concept of the project.
- Remove the input tags and their styling.
- Style the Range input according to the theme of the web page.
- **Important:** Make sure any of your changes doesn't affect remaining contents of the web page.

## Tasks checker
- [ ] Change the Input type from `text` to range.
- [ ] Remove *(or)* modify the CSS of Range input type Input.
- [ ] Check whether your changes are effecting other elements or not. ***(Including [w3c validator](https://validator.w3.org/#validate_by_upload "Check using w3c validator"))***

## Reference
Check this sample YouTube video to get an Idea about how you can style the Range Input tag: 
> [Custom Animated Range Slider using HTML CSS & JavaScript](https://www.youtube.com/watch?v=3Eb6FtjkZ_k)
